name: Artifact PRs

on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: 'Base branch'
        required: true
        default: 'main'
      compare_branch:
        description: 'Compare branch'
        required: true
        default: 'develop'

jobs:
  list_prs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Fetch branches
      run: |
        git fetch origin ${{ github.event.inputs.base_branch }}
        git fetch origin ${{ github.event.inputs.compare_branch }}

    - name: Calculate PR diff
      run: |
        git diff origin/${{ github.event.inputs.base_branch }}..origin/${{ github.event.inputs.compare_branch }} > mydiff.txt
        sh 'echo "Diff of branches ...."'
        sh "cat mydiff.txt"
    - name: Upload diff as artifact
      uses: actions/upload-artifact@v3
      with:
        name: pr-diff
        path: mydiff.txt
