name: Artifact PRs

on:
  workflow_dispatch:
    inputs:
       base_branch:
         description: 'Base branch'
         required: true
         default: 'main'
       compare_branch:
         description: 'Compare branch'
         required: true
         default: 'develop'
runs-on: ubuntu-latest

jobs:
  list_prs:
    steps:
    - name: Fetch main branch
      shell: bash
      run: |
      git fetch origin main
  get_diff:
    steps:
    - name: Calculate PR diff
      shell: bash
      run: |
      git diff origin/main..develop > mydiff
  artifact:
    - name: Artifact the diff
      uses: actions/upload-artifact@v3
      with:
        name: pr-list
        path: pr-list.txt
